platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 2.7.13-wheezy
inputs:
- name: stock-ami
- name: brkt-pcf-pipelines
outputs:
- name: ami
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  REGION:
  SERVICE_DOMAIN:
  WRAP_ARGS:
  EMAIL:
  PASSWORD:
  METAVISOR_VERSION:
  ENCRYPTOR_AMI:
run:
  path: brkt-pcf-pipelines/tasks/wrap-ami/task.sh
