platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 2.7.13-wheezy
inputs:
- name: stock-ami
- name: brkt-pcf-pipelines
- name: encrypted-amis
outputs:
- name: results
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  REGION:
  URL:
  EMAIL:
  PASSWORD:
  METAVISOR_VERSION:
run:
  path: brkt-pcf-pipelines/tasks/encrypt-ami/task.sh
